pipeline {
    agent any

    tools {
        jdk 'jdk21'
        maven 'maven3'
    }

    environment {
        SONAR_SERVER = 'sonar-server'
        AWS_REGION = 'ap-south-1'
        ECR_REPO = '538782572682.dkr.ecr.ap-south-1.amazonaws.com/devops-project'
        IMAGE_TAG = "latest"
    }

    stages {

        stage('Checkout Code') {
            steps {
                git branch: 'main', url: 'https://github.com/Pkadam422/new-spring-demo-project.git'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('sonar-server') {
                    sh '''
                    mvn sonar:sonar \
                    -Dsonar.projectKey=devops-project \
                    -Dsonar.host.url=http://3.109.2.196:9000 \
                    -Dsonar.login=$SONAR_AUTH_TOKEN
                    '''
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time: 2, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }
        stage('Docker Build') {
            steps {
                sh 'docker build -t devops-demo -f docker/Dockerfile .'
            }
         } 
        stage('ECR Login') {
    steps {
        sh '''
        aws ecr get-login-password --region $AWS_REGION | \
        docker login --username AWS --password-stdin $ECR_REPO
        '''
        }
      }
      stage('Tag Image') {
    steps {
        sh 'docker tag devops-demo:latest $ECR_REPO:latest'
         }
        }

       stage('Push to ECR') {
         steps {
        sh 'docker push $ECR_REPO:latest'
       }
     }
    }
}